import { prisma } from "../lib/prisma/prisma";

const grimoireRituals = [
  {
    title: "Amarre de Tilma y Huipil Mexica",
    slug: "amarre-tilma-huipil-mexica",
    summary:
      "Ritual ancestral nahua-mexica para unir irrevocablemente a dos personas en amor y compromiso eterno, inspirado en las ceremonias matrimoniales prehispánicas.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    origin:
      "Tradición mexica prehispánica, documentada en el Códice Mendocino. En la cultura mexica, el amarre de tilma del hombre y huipil de la mujer simbolizaba la unión cósmica de dos almas para toda la eternidad.",
    intention:
      "Atar el destino amoroso de dos personas de forma permanente y fiel.",
    expectedResult:
      "La persona deseada regresa o se une completamente, con lealtad inquebrantable.",
    repeatEvery: "Luna nueva",
    tags: ["amarre", "mexica", "tilma", "huipil", "unión"],
    ingredients: [
      "Trozo de tela roja (representando tilma)",
      "Trozo de tela blanca (representando huipil)",
      "Mechón de cabello de ambos",
      "Cuerda de ixtle o hilo rojo",
      "Velas rojas (2)",
      "Pétalos de cempasúchil",
      "Foto o nombre escrito de la persona",
      "Copal",
    ],
    steps: [
      "1. Enciende las dos velas rojas en el altar dedicado.",
      "2. Coloca la tela roja y blanca una sobre la otra en forma de cruz.",
      "3. Ata los mechones de cabello juntos con el hilo rojo pronunciando nombres.",
      "4. Envuelve las telas alrededor de los cabellos y la foto o papel.",
      "5. Ata fuertemente formando siete nudos mientras repites el ensalmo mexica.",
      "6. Esparce pétalos de cempasúchil alrededor del paquete completo.",
      "7. Invoca a Xochiquetzal y Xochipilli para bendecir la unión eterna.",
      "8. Entierra el paquete en tierra fértil cerca de un árbol antiguo o guárdalo en lugar oscuro y seguro.",
      "9. Repite la invocación completa durante 7 noches consecutivas al atardecer.",
      "10. Mantén una vela roja encendida cada noche hasta consumirse.",
      "11. Visualiza la unión completa y los lazos invisibles fortaleciéndose.",
      "12. Ofrece copal a los ancestros mexicas pidiendo su bendición.",
      "13. Refuerza cada nudo mentalmente si sientes debilidad en la conexión.",
      "14. Da gracias a las deidades al finalizar cada sesión nocturna.",
      "15. Observa señales de aproximación o sueños reveladores.",
      "16. Repite el ritual completo en la siguiente luna nueva si los resultados son parciales.",
      "17. Protege el paquete de miradas ajenas y energías negativas.",
      "18. Alimenta el amarre con una gota de miel cada 3 días.",
      "19. Recita el ensalmo completo de unión mexica tres veces al día.",
      "20. Cierra con gratitud profunda y limpia el altar con agua bendita.",
    ],
    warnings:
      "Este amarre es de fuerte dominio; úsalo solo con intención pura o puede revertir con consecuencias graves.",
    notes:
      "Respeta el libre albedrío; consecuencias kármicas posibles en la tradición mexica.",
    essenceCost: 250,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 1,
  },
  {
    title: "Endulzamiento con Miel y Canela de Brujería Mexicana",
    slug: "endulzamiento-miel-canela-brujeria",
    summary:
      "Ritual de endulzamiento tradicional para suavizar el corazón de una persona, hacerla más cariñosa y dócil en relaciones amorosas o familiares.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 40,
    origin:
      "Brujería popular mexicana, sincretismo indígena y católico. Práctica común en Veracruz y regiones rurales usada por curanderos.",
    intention: "Endulzar el carácter y sentimientos hacia uno.",
    expectedResult: "La persona se vuelve más atenta, amorosa y receptiva.",
    repeatEvery: "Cada viernes",
    tags: ["endulzamiento", "miel", "canela", "amor", "suavizar"],
    ingredients: [
      "Miel pura (frasco pequeño)",
      "Canela en polvo o rama",
      "Foto de la persona",
      "Velas rosas (3)",
      "Azúcar morena",
      "Papel de amate",
      "Agua de rosas",
      "Copal",
    ],
    steps: [
      "1. Enciende las tres velas rosas formando triángulo.",
      "2. Vierte miel pura en un plato de barro limpio.",
      "3. Esparce canela en polvo abundantemente sobre la miel.",
      "4. Coloca la foto de la persona boca arriba en el centro del plato.",
      "5. Espolvorea azúcar morena formando un círculo protector alrededor.",
      "6. Rocía agua de rosas mientras recitas el nombre completo 21 veces.",
      "7. Mezcla todo suavemente con el dedo índice de la mano derecha.",
      "8. Invoca a la Virgen de Guadalupe o Xochiquetzal para guiar el ritual.",
      "9. Deja reposar la mezcla bajo las velas durante 21 minutos exactos.",
      "10. Unta un poco de la mezcla en la esquina de la foto.",
      "11. Guarda el resto de la mezcla en un frasco de vidrio sellado.",
      "12. Repite el ritual completo durante 9 días seguidos al amanecer.",
      "13. Ofrece flores frescas cada día frente al altar.",
      "14. Visualiza la dulzura fluyendo del corazón de la persona hacia ti.",
      "15. Quema una vela rosa diaria hasta que se consuma.",
      "16. Da gracias con copal al finalizar cada sesión.",
      "17. Alimenta la mezcla con más miel fresca cada tercer día.",
      "18. Observa cambios sutiles en el comportamiento y comunicación.",
      "19. Refuerza el ritual si los resultados tardan en manifestarse.",
      "20. Cierra el ciclo completo con gratitud profunda y limpia el espacio.",
    ],
    warnings:
      "No ingerir la mezcla bajo ninguna circunstancia; uso externo únicamente.",
    notes: "Usar con amor genuino, no para manipulación pura.",
    essenceCost: 180,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 2,
  },
  {
    title: "Amarre con Listón Rojo y Manzana Roja",
    slug: "amarre-liston-rojo-manzana",
    summary:
      "Poderoso amarre amoroso popular en México usando listón rojo y manzana para atraer y atar a la persona deseada.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 50,
    origin:
      "Folklore mestizo mexicano. Práctica extendida en todo México combinando elementos católicos y prehispánicos.",
    intention: "Atar emocional y físicamente a la persona.",
    expectedResult: "Regreso rápido y fidelidad intensa.",
    repeatEvery: "Luna creciente",
    tags: ["amarre", "liston-rojo", "manzana", "amor"],
    ingredients: [
      "Listón rojo (1 metro)",
      "Manzana roja grande",
      "Agujas nuevas (7)",
      "Foto o nombre escrito",
      "Velas rojas (2)",
      "Chile seco (3)",
      "Sal gruesa",
    ],
    steps: [
      "1. Corta la manzana roja por la mitad con cuidado.",
      "2. Coloca la foto o papel con nombres dentro de la manzana.",
      "3. Une las mitades firmemente con el listón rojo.",
      "4. Ata siete nudos fuertes mientras invocas el nombre.",
      "5. Clava las siete agujas atravesando completamente la manzana.",
      "6. Esparce sal gruesa y chile seco alrededor del ritual.",
      "7. Enciende las dos velas rojas a los lados.",
      "8. Recita el ensalmo de amarre popular 21 veces sin parar.",
      "9. Entierra la manzana en un patio o maceta profunda.",
      "10. Mantén las velas encendidas durante 7 noches consecutivas.",
      "11. Invoca santos del amor o deidades mexicas.",
      "12. Visualiza el lazo rojo atando corazones para siempre.",
      "13. Refuerza los nudos mentalmente cada noche.",
      "14. Ofrece copal y tabaco a los espíritus ayudantes.",
      "15. Observa señales de contacto o sueños.",
      "16. Repite el entierro si es necesario en luna siguiente.",
      "17. Protege el sitio de entierro con sal.",
      "18. Da gracias completas al terminar el ciclo.",
      "19. Limpia energías residuales con limpia de huevo.",
      "20. Cierra el ritual sellando con cera de vela.",
    ],
    warnings: "Puede generar obsesión fuerte; usa solo cuando estés seguro.",
    notes: "Consecuencias en el equilibrio cósmico mexicano.",
    essenceCost: 220,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 3,
  },
  {
    title: "Separación con Limón y Sal Gruesa",
    slug: "separacion-limon-sal",
    summary:
      "Ritual de separación para alejar parejas o influencias no deseadas, basado en tradiciones de brujería mexicana.",
    category: "SEPARATION",
    accessLevel: "PREMIUM",
    difficulty: "ADVANCED",
    estimatedMinutes: 55,
    origin:
      "Brujería rural mexicana. Usado para romper lazos tóxicos, común en limpias y trabajos de curanderos.",
    intention: "Cortar lazos energéticos entre personas.",
    expectedResult: "Distanciamiento natural y pacífico.",
    repeatEvery: "Luna menguante",
    tags: ["separacion", "limon", "sal", "corte", "limpia"],
    ingredients: [
      "Limones amarillos (3)",
      "Sal gruesa (puñado grande)",
      "Agujas negras (9)",
      "Papel con nombres",
      "Velas negras (2)",
      "Hilo negro grueso",
      "Copal",
    ],
    steps: [
      "1. Corta cada limón en forma de cruz profunda.",
      "2. Coloca el papel con nombres dentro de cada limón.",
      "3. Esparce sal gruesa abundantemente en el interior.",
      "4. Clava las agujas negras atravesando los limones.",
      "5. Ata fuertemente con hilo negro cada limón.",
      "6. Enciende las velas negras en el altar.",
      "7. Recita la oración tradicional de separación tres veces.",
      "8. Exprime jugo de limón mientras visualizas cortar lazos.",
      "9. Entierra los limones lejos de tu casa en lugar desierto.",
      "10. Repite el ritual completo durante 9 días menguantes.",
      "11. Limpia el espacio con humo de copal después de cada sesión.",
      "12. Invoca protección de arcángeles o espíritus guardianes.",
      "13. Quema los papeles sobrantes al final de cada día.",
      "14. Observa el distanciamiento progresivo.",
      "15. Refuerza con sal alrededor de tu hogar.",
      "16. Da gracias a las fuerzas que ayudan en la separación.",
      "17. Protege tu propia energía con limpia personal.",
      "18. Cierra el ciclo completo con agua bendita.",
      "19. Realiza una limpia general del hogar.",
      "20. Confirma resultados con meditación profunda.",
    ],
    warnings: "No usar en parejas propias sin profunda reflexión previa.",
    notes: "Respeta el karma y libre albedrío de todos.",
    essenceCost: 280,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 4,
  },
  {
    title: "Dominación con Polvos de Rancho",
    slug: "dominacion-polvos-rancho",
    summary:
      "Trabajo de dominación fuerte para controlar situaciones o voluntades usando polvos tradicionales de brujería de rancho.",
    category: "DOMINATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 70,
    origin:
      "Brujería de rancho mexicana, Veracruz y Catemaco. Prácticas de control usadas por brujos de rancho.",
    intention: "Dominar voluntad o circunstancias a favor propio.",
    expectedResult: "Sumisión o control deseado en la situación.",
    repeatEvery: "Martes y viernes",
    tags: ["dominacion", "polvos", "control", "rancho"],
    ingredients: [
      "Polvos de dominación (hierbas secas, ajo, chile)",
      "Veladora roja grande",
      "Foto de la persona",
      "Aceite de mandrágora o domina",
      "Clavos de olor (13)",
      "Copal",
    ],
    steps: [
      "1. Unta completamente la veladora con aceite de domina.",
      "2. Esparce polvos de dominación en forma de cruz.",
      "3. Clava los 13 clavos en la foto o nombre.",
      "4. Enciende la veladora roja grande.",
      "5. Recita los mandamientos de dominio 13 veces.",
      "6. Visualiza el control total sobre la persona o situación.",
      "7. Repite el trabajo completo durante 13 días.",
      "8. Ofrece tabaco y copal a los espíritus de rancho.",
      "9. Mantén el altar en lugar oscuro y privado.",
      "10. Refuerza con más polvos cada tres días.",
      "11. Invoca santos fuertes como San Marcos o San Cipriano.",
      "12. Quema incienso de mirra diariamente.",
      "13. Observa signos de obediencia y sumisión.",
      "14. Protege contra posibles reversas con sal.",
      "15. Da gracias profundas al terminar cada sesión.",
      "16. Limpia residuos energéticos con huevo.",
      "17. Almacena polvos restantes en frasco oscuro.",
      "18. Repite el ritual según la necesidad específica.",
      "19. Cierra con círculo de sal protector.",
      "20. Reflexiona sobre las implicaciones éticas profundas.",
    ],
    warnings:
      "Alta reversibilidad y fuerte costo kármico; no recomendado para principiantes.",
    notes: "Uso responsable y solo en casos justificados.",
    essenceCost: 300,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 5,
  },
  {
    title: "Endulzamiento con Piloncillo Ancestral",
    slug: "endulzamiento-piloncillo-ancestral",
    summary:
      "Endulzamiento profundo usando piloncillo para suavizar tensiones en parejas, familia o negocios.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 35,
    origin:
      "Tradición mexicana de rancho y mercados. Piloncillo o chiancaca usado en hechizos desde época colonial.",
    intention: "Traer dulzura, armonía y cariño.",
    expectedResult: "Mejora notable en relaciones y comunicación.",
    repeatEvery: "Miércoles",
    tags: ["endulzamiento", "piloncillo", "armonia", "dulzura"],
    ingredients: [
      "Piloncillo (trozo grande)",
      "Miel de abeja",
      "Canela en rama",
      "Velas rosadas (2)",
      "Nombres escritos en amate",
      "Agua florida",
    ],
    steps: [
      "1. Enciende las velas rosadas en altar limpio.",
      "2. Derrite lentamente el piloncillo en recipiente.",
      "3. Agrega miel de abeja y canela en rama.",
      "4. Coloca los nombres escritos en el centro.",
      "5. Mezcla todo con dedo índice derecho en sentido horario.",
      "6. Recita oración de dulzura ancestral tres veces.",
      "7. Deja enfriar la mezcla completamente.",
      "8. Unta un poco en objetos personales de la persona.",
      "9. Repite el endulzamiento durante 7 días seguidos.",
      "10. Ofrece flores o fruta a las deidades del amor.",
      "11. Visualiza dulzura y armonía fluyendo.",
      "12. Quema velas rosadas diariamente.",
      "13. Guarda la mezcla en frasco sellado.",
      "14. Observa mejoras en actitudes.",
      "15. Refuerza semanalmente si es necesario.",
      "16. Da gracias con copal al finalizar.",
      "17. Limpia altar con agua florida.",
      "18. Cierra el ritual con gratitud.",
      "19. Comparte dulzura en la vida diaria.",
      "20. Mantén pensamientos positivos constantes.",
    ],
    warnings: "Efecto temporal; requiere refuerzos.",
    notes: "Ideal para sanar relaciones existentes.",
    essenceCost: 160,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 6,
  },
  {
    title: "Amarre con Cabello y Chile Mexicano",
    slug: "amarre-cabello-chile",
    summary:
      "Amarre ardiente y fuerte usando cabello y chiles para pasión y lealtad.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 45,
    origin:
      "Folklore popular del centro de México. Variante picante usada por brujos.",
    intention: "Atar con fuego de pasión intensa.",
    expectedResult: "Deseo y retorno apasionado.",
    repeatEvery: "Viernes de luna creciente",
    tags: ["amarre", "cabello", "chile", "pasión"],
    ingredients: [
      "Mechón de cabello",
      "Chiles secos (7)",
      "Listón rojo",
      "Velas rojas",
      "Agujas",
    ],
    steps: [
      "1. Enciende velas rojas.",
      "2. Ata mechón de cabello con listón.",
      "3. Envuelve con chiles secos.",
      "4. Clava agujas atravesando.",
      "5. Recita ensalmo ardiente.",
      "6. Visualiza fuego de pasión.",
      "7. Repite 9 noches.",
      "8. Ofrece copal.",
      "9. Entierra paquete.",
      "10. Mantén velas.",
      "11. Refuerza visualización.",
      "12. Invoca Xochiquetzal.",
      "13. Observa señales.",
      "14. Protege ritual.",
      "15. Da gracias.",
      "16. Limpia espacio.",
      "17. Repite si débil.",
      "18. Alimenta con miel.",
      "19. Cierra nudos.",
      "20. Finaliza con sal.",
    ],
    warnings: "Genera intensidad; controlar.",
    notes: "Ardiente variante de brujería mexicana.",
    essenceCost: 230,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 7,
  },
  {
    title: "Separación con Huevo y Ajo",
    slug: "separacion-huevo-ajo",
    summary:
      "Ritual de separación usando huevo y ajo para romper influencias negativas.",
    category: "SEPARATION",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    origin:
      "Limpias tradicionales mexicanas. Parte de curanderismo para eliminar lazos tóxicos.",
    intention: "Eliminar conexiones dañinas.",
    expectedResult: "Liberación y paz.",
    repeatEvery: "Luna menguante",
    tags: ["separacion", "huevo", "ajo", "limpia"],
    ingredients: ["Huevos (3)", "Ajos (7)", "Sal", "Velas negras", "Papel"],
    steps: [
      "1. Pasa huevo por cuerpo.",
      "2. Rompe en plato con ajo.",
      "3. Esparce sal.",
      "4. Enciende velas.",
      "5. Recita corte.",
      "6. Entierra.",
      "7. Repite 7 días.",
      "8. Limpia con copal.",
      "9. Observa.",
      "10. Refuerza.",
      "11. Da gracias.",
      "12. Protege.",
      "13. Quema papel.",
      "14. Limpia hogar.",
      "15. Cierra.",
      "16. Visualiza libertad.",
      "17. Ofrece.",
      "18. Repite.",
      "19. Finaliza.",
      "20. Confirma.",
    ],
    warnings: "Limpia personal requerida.",
    notes: "Clásico para rupturas en curanderismo mexicano.",
    essenceCost: 190,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 8,
  },
  {
    title: "Dominación con Veladora y San Marcos",
    slug: "dominacion-san-marcos",
    summary: "Dominación invocando San Marcos para control y obediencia.",
    category: "DOMINATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 65,
    origin:
      "Sincretismo católico-mexicano. Uso común de santos en brujería para dominar.",
    intention: "Controlar mediante intercesión.",
    expectedResult: "Obediencia.",
    repeatEvery: "Martes",
    tags: ["dominacion", "san-marcos", "veladora"],
    ingredients: ["Veladora de San Marcos", "Foto", "Aceite", "Polvos"],
    steps: [
      "1. Unta veladora.",
      "2. Coloca foto.",
      "3. Enciende.",
      "4. Invoca San Marcos.",
      "5. Recita 13 veces.",
      "6. Visualiza.",
      "7. Repite 13 días.",
      "8. Ofrece.",
      "9. Refuerza.",
      "10. Observa.",
      "11. Protege.",
      "12. Da gracias.",
      "13. Limpia.",
      "14. Almacena.",
      "15. Repite.",
      "16. Cierra.",
      "17. Reflexiona.",
      "18. Invoca.",
      "19. Finaliza.",
      "20. Agradece.",
    ],
    warnings: "Fuerte reversa posible.",
    notes: "Solo para justicia.",
    essenceCost: 290,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 9,
  },
  {
    title: "Endulzamiento con Vainilla y Rosas",
    slug: "endulzamiento-vainilla-rosas",
    summary: "Endulzamiento suave con vainilla y rosas para atraer cariño.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 30,
    origin: "Folklore mexicano. Uso de flores y vainilla en magia amorosa.",
    intention: "Suavizar y atraer.",
    expectedResult: "Cariño aumentado.",
    repeatEvery: "Viernes",
    tags: ["endulzamiento", "vainilla", "rosas"],
    ingredients: ["Vainilla", "Rosas rojas", "Miel", "Velas"],
    steps: [
      "1. Enciende velas.",
      "2. Prepara mezcla.",
      "3. Coloca nombres.",
      "4. Mezcla.",
      "5. Recita.",
      "6. Deja.",
      "7. Unta.",
      "8. Repite.",
      "9. Ofrece rosas.",
      "10. Visualiza.",
      "11. Quema.",
      "12. Guarda.",
      "13. Observa.",
      "14. Refuerza.",
      "15. Gracias.",
      "16. Limpia.",
      "17. Cierra.",
      "18. Comparte.",
      "19. Mantén.",
      "20. Finaliza.",
    ],
    warnings: "Suave y temporal.",
    notes: "Buen uso para sanar.",
    essenceCost: 170,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 10,
  },
  {
    title: "Amarre con Mechón y Listón Negro",
    slug: "amarre-mechon-liston-negro",
    summary:
      "Amarre oscuro de dominación usando mechón de cabello y listón negro para control total en relaciones.",
    category: "BINDING",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 75,
    origin:
      "Brujería tradicional de Catemaco y Veracruz. Práctica de amarre fuerte documentada en tradiciones veracruzanas de brujería mestiza.",
    intention: "Atar voluntad y acciones de la persona.",
    expectedResult: "Control y sumisión completa.",
    repeatEvery: "Luna nueva",
    tags: ["amarre", "dominio", "liston-negro", "control"],
    ingredients: [
      "Mechón de cabello de la persona",
      "Listón negro (1 metro)",
      "Agujas negras (13)",
      "Velas negras (3)",
      "Chile negro seco",
      "Sal negra",
      "Foto",
    ],
    steps: [
      "1. Enciende las tres velas negras en triángulo.",
      "2. Ata el mechón de cabello firmemente con listón negro.",
      "3. Envuelve la foto dentro del nudo principal.",
      "4. Clava las 13 agujas negras atravesando todo.",
      "5. Esparce sal negra y chile seco alrededor.",
      "6. Recita el conjuro de amarre oscuro 21 veces.",
      "7. Visualiza cadenas invisibles atando a la persona.",
      "8. Entierra el paquete en un cruce de caminos o lugar oscuro.",
      "9. Mantén velas encendidas durante 13 noches.",
      "10. Invoca espíritus de dominación mexicas.",
      "11. Refuerza nudos cada noche con más listón.",
      "12. Ofrece tabaco y aguardiente a los guardianes.",
      "13. Observa comportamientos de obediencia.",
      "14. Protege el ritual contra interferencias.",
      "15. Da gracias a las fuerzas oscuras ayudantes.",
      "16. Limpia tu espacio con copal fuerte.",
      "17. Repite el entierro si los lazos se debilitan.",
      "18. Alimenta con gotas de sangre propia (opcional).",
      "19. Recita ensalmo diario al amanecer.",
      "20. Cierra sellando con cera negra y sal.",
    ],
    warnings: "Muy fuerte y con alto riesgo de reversa o obsesión mutua.",
    notes: "Uso solo en casos extremos; alto costo espiritual.",
    essenceCost: 300,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 11,
  },
  {
    title: "Endulzamiento con Azúcar Morena y Canela",
    slug: "endulzamiento-azucar-morena-canela",
    summary:
      "Endulzamiento para suavizar corazón y atraer afecto familiar o romántico.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 38,
    origin:
      "Folklore mestizo mexicano. Común en hogares mexicanos para resolver pleitos y traer paz.",
    intention: "Endulzar relaciones tensas.",
    expectedResult: "Mayor cariño y comprensión.",
    repeatEvery: "Jueves",
    tags: ["endulzamiento", "azucar", "canela", "paz"],
    ingredients: [
      "Azúcar morena",
      "Canela en polvo",
      "Velas rosas",
      "Foto",
      "Miel",
    ],
    steps: [
      "1. Enciende velas rosas.",
      "2. Vierte azúcar morena.",
      "3. Agrega canela.",
      "4. Coloca foto.",
      "5. Mezcla con miel.",
      "6. Recita oración.",
      "7. Deja 21 minutos.",
      "8. Unta foto.",
      "9. Repite 9 días.",
      "10. Ofrece.",
      "11. Visualiza.",
      "12. Quema velas.",
      "13. Guarda.",
      "14. Observa.",
      "15. Refuerza.",
      "16. Gracias.",
      "17. Limpia.",
      "18. Cierra.",
      "19. Comparte.",
      "20. Mantén.",
    ],
    warnings: "Reforzar periódicamente.",
    notes: "Para armonía positiva.",
    essenceCost: 155,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 12,
  },
  {
    title: "Separación con Gallina Negra",
    slug: "separacion-gallina-negra",
    summary:
      "Ritual fuerte de separación usando gallina negra para cortar lazos profundos.",
    category: "SEPARATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 90,
    origin:
      "Brujería indígena y africana sincretizada en México. Práctica en zonas rurales para romper uniones perjudiciales.",
    intention: "Eliminar influencia tóxica.",
    expectedResult: "Ruptura definitiva.",
    repeatEvery: "Luna menguante",
    tags: ["separacion", "gallina", "negra", "corte"],
    ingredients: [
      "Gallina negra",
      "Cuchillo ritual",
      "Velas negras",
      "Sal",
      "Hilo negro",
    ],
    steps: [
      "1. Purifica espacio.",
      "2. Invoca fuerzas.",
      "3. Pasa gallina por cuerpos.",
      "4. Recita corte.",
      "5. Sacrificio simbólico.",
      "6. Entierra con nombres.",
      "7. Enciende velas.",
      "8. Repite 7 días.",
      "9. Limpia.",
      "10. Observa.",
      "11. Refuerza.",
      "12. Protege.",
      "13. Da gracias.",
      "14. Cierra.",
      "15. Limpia personal.",
      "16. Quema restos.",
      "17. Sal en casa.",
      "18. Visualiza.",
      "19. Ofrece.",
      "20. Confirma.",
    ],
    warnings: "Requiere experiencia; fuerte energía.",
    notes: "Solo para protección.",
    essenceCost: 1000,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 13,
  },
  {
    title: "Dominación con San Cipriano",
    slug: "dominacion-san-cipriano",
    summary: "Dominación invocando a San Cipriano para control mágico.",
    category: "DOMINATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 60,
    origin:
      "Tradición católico-brujería. San Cipriano usado en México para trabajos de dominio.",
    intention: "Dominar mediante santo.",
    expectedResult: "Control efectivo.",
    repeatEvery: "Sábado",
    tags: ["dominacion", "san-cipriano", "santo"],
    ingredients: ["Veladora San Cipriano", "Foto", "Aceite", "Polvos"],
    steps: [
      "1. Enciende veladora.",
      "2. Coloca foto.",
      "3. Unta aceite.",
      "4. Invoca Cipriano.",
      "5. Recita.",
      "6. Visualiza.",
      "7. Repite.",
      "8. Ofrece.",
      "9. Refuerza.",
      "10. Observa.",
      "11. Protege.",
      "12. Gracias.",
      "13. Limpia.",
      "14. Almacena.",
      "15. Repite.",
      "16. Cierra.",
      "17. Reflexiona.",
      "18. Invoca.",
      "19. Finaliza.",
      "20. Agradece.",
    ],
    warnings: "Poderoso santo; respeto máximo.",
    notes: "Solo para justicia.",
    essenceCost: 270,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 14,
  },
  {
    title: "Endulzamiento con Manzana y Miel",
    slug: "endulzamiento-manzana-miel",
    summary: "Endulzamiento usando manzana para atraer dulzura amorosa.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 45,
    origin: "Folklore mexicano. Manzana en rituales de amor mestizos.",
    intention: "Endulzar persona.",
    expectedResult: "Afecto.",
    repeatEvery: "Lunes",
    tags: ["endulzamiento", "manzana", "miel"],
    ingredients: ["Manzana", "Miel", "Canela", "Velas"],
    steps: [
      "1. Corta manzana.",
      "2. Unta miel.",
      "3. Esparce canela.",
      "4. Coloca nombres.",
      "5. Enciende velas.",
      "6. Recita.",
      "7. Deja.",
      "8. Come parte.",
      "9. Repite.",
      "10. Ofrece.",
      "11. Visualiza.",
      "12. Guarda.",
      "13. Observa.",
      "14. Refuerza.",
      "15. Gracias.",
      "16. Limpia.",
      "17. Cierra.",
      "18. Comparte.",
      "19. Mantén.",
      "20. Finaliza.",
    ],
    warnings: "Simple.",
    notes: "Positivo.",
    essenceCost: 165,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 15,
  },
  {
    title: "Amarre con Hilo Rojo y Fotografía",
    slug: "amarre-hilo-rojo-foto",
    summary: "Amarre clásico con hilo rojo para unir destinos.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 50,
    origin:
      "Tradición popular mexicana. Hilo rojo en magia amorosa universal adaptada en México.",
    intention: "Unir fuertemente.",
    expectedResult: "Unión.",
    repeatEvery: "Luna creciente",
    tags: ["amarre", "hilo-rojo", "foto"],
    ingredients: ["Hilo rojo", "Foto", "Velas", "Nombres"],
    steps: [
      "1. Enciende velas.",
      "2. Ata fotos.",
      "3. Nudos.",
      "4. Recita.",
      "5. Visualiza.",
      "6. Repite.",
      "7. Ofrece.",
      "8. Entierra.",
      "9. Mantén.",
      "10. Refuerza.",
      "11. Invoca.",
      "12. Observa.",
      "13. Protege.",
      "14. Gracias.",
      "15. Limpia.",
      "16. Repite.",
      "17. Alimenta.",
      "18. Cierra.",
      "19. Sellado.",
      "20. Final.",
    ],
    warnings: "Fuerte lazo.",
    notes: "Cautela.",
    essenceCost: 210,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 16,
  },
  {
    title: "Separación con Sal y Limón",
    slug: "separacion-sal-limon",
    summary: "Separación rápida usando sal y limón.",
    category: "SEPARATION",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    origin: "Limpias mexicanas. Elementos básicos en curanderismo.",
    intention: "Cortar.",
    expectedResult: "Distanciamiento.",
    repeatEvery: "Menguante",
    tags: ["separacion", "sal", "limon"],
    ingredients: ["Limones", "Sal", "Velas negras"],
    steps: [
      "1. Corta limones.",
      "2. Sal dentro.",
      "3. Nombres.",
      "4. Velas.",
      "5. Recita.",
      "6. Exprime.",
      "7. Entierra.",
      "8. Repite.",
      "9. Limpia.",
      "10. Observa.",
      "11. Refuerza.",
      "12. Gracias.",
      "13. Protege.",
      "14. Quema.",
      "15. Sal casa.",
      "16. Visualiza.",
      "17. Ofrece.",
      "18. Cierra.",
      "19. Limpia.",
      "20. Confirma.",
    ],
    warnings: "Efectivo.",
    notes: "Protección.",
    essenceCost: 185,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 17,
  },
  {
    title: "Dominación con Polvos de Chile",
    slug: "dominacion-polvos-chile",
    summary: "Dominación picante con polvos de chile.",
    category: "DOMINATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 55,
    origin: "Brujería rancho. Chile para ardor de dominio.",
    intention: "Control ardiente.",
    expectedResult: "Sumisión.",
    repeatEvery: "Martes",
    tags: ["dominacion", "chile", "polvos"],
    ingredients: ["Chiles", "Polvos", "Veladora"],
    steps: [
      "1. Unta.",
      "2. Esparce polvos.",
      "3. Enciende.",
      "4. Invoca.",
      "5. Recita.",
      "6. Visualiza.",
      "7. Repite.",
      "8. Ofrece.",
      "9. Refuerza.",
      "10. Observa.",
      "11. Protege.",
      "12. Gracias.",
      "13. Limpia.",
      "14. Almacena.",
      "15. Repite.",
      "16. Cierra.",
      "17. Reflexiona.",
      "18. Invoca.",
      "19. Finaliza.",
      "20. Agradece.",
    ],
    warnings: "Intenso.",
    notes: "Cuidado.",
    essenceCost: 260,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 18,
  },
  {
    title: "Endulzamiento con Rosas y Azúcar",
    slug: "endulzamiento-rosas-azucar",
    summary: "Endulzamiento floral con rosas.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 35,
    origin: "Folklore. Rosas en amor mexicano.",
    intention: "Dulzura floral.",
    expectedResult: "Cariño.",
    repeatEvery: "Viernes",
    tags: ["endulzamiento", "rosas", "azucar"],
    ingredients: ["Rosas", "Azúcar", "Miel"],
    steps: [
      "1. Enciende.",
      "2. Pétalos.",
      "3. Azúcar.",
      "4. Miel.",
      "5. Nombres.",
      "6. Recita.",
      "7. Mezcla.",
      "8. Deja.",
      "9. Unta.",
      "10. Repite.",
      "11. Ofrece.",
      "12. Visualiza.",
      "13. Guarda.",
      "14. Observa.",
      "15. Refuerza.",
      "16. Gracias.",
      "17. Limpia.",
      "18. Cierra.",
      "19. Comparte.",
      "20. Finaliza.",
    ],
    warnings: "Suave.",
    notes: "Amor.",
    essenceCost: 175,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 19,
  },
  {
    title: "Amarre Eterno con Cuerda de Ixtle",
    slug: "amarre-eterno-ixtle",
    summary: "Amarre eterno prehispánico con cuerda de ixtle.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 65,
    origin: "Tradición nahua. Cuerdas en rituales mexicas.",
    intention: "Unión eterna.",
    expectedResult: "Permanencia.",
    repeatEvery: "Luna llena",
    tags: ["amarre", "ixtle", "eterno"],
    ingredients: ["Cuerda ixtle", "Telas", "Cabello"],
    steps: [
      "1. Enciende.",
      "2. Ata.",
      "3. Nudos.",
      "4. Invoca.",
      "5. Visualiza.",
      "6. Repite.",
      "7. Ofrece.",
      "8. Entierra.",
      "9. Mantén.",
      "10. Refuerza.",
      "11. Ancestros.",
      "12. Observa.",
      "13. Protege.",
      "14. Gracias.",
      "15. Limpia.",
      "16. Repite.",
      "17. Alimenta.",
      "18. Cierra.",
      "19. Sellado.",
      "20. Eterno.",
    ],
    warnings: "Permanente.",
    notes: "Respeto.",
    essenceCost: 245,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 20,
  },
  {
    title: "Amarre con Aguja y Limón para Pasión",
    slug: "amarre-aguja-limon-pasion",
    summary:
      "Amarre ardiente usando limón y agujas para encender pasión y fidelidad intensa.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 50,
    origin:
      "Folklore popular mexicano. Variante común en el centro y sur de México para atraer con fuego.",
    intention: "Atar con deseo ardiente.",
    expectedResult: "Pasión y retorno rápido.",
    repeatEvery: "Viernes",
    tags: ["amarre", "limon", "aguja", "pasion"],
    ingredients: [
      "Limones (3)",
      "Agujas (9)",
      "Listón rojo",
      "Velas rojas (2)",
      "Chile seco",
      "Foto",
    ],
    steps: [
      "1. Corta los limones en cruz.",
      "2. Inserta la foto o nombre dentro.",
      "3. Clava las agujas atravesando.",
      "4. Ata con listón rojo fuerte.",
      "5. Esparce chile seco alrededor.",
      "6. Enciende velas rojas.",
      "7. Recita conjuro de pasión 21 veces.",
      "8. Exprime jugo visualizando fuego.",
      "9. Entierra los limones en maceta.",
      "10. Mantén velas encendidas 7 noches.",
      "11. Invoca deidades del amor.",
      "12. Visualiza la pasión consumiendo.",
      "13. Refuerza agujas mentalmente.",
      "14. Ofrece copal cada noche.",
      "15. Observa señales de deseo.",
      "16. Repite en siguiente luna si es débil.",
      "17. Protege el lugar con sal.",
      "18. Da gracias al terminar.",
      "19. Limpia energías con huevo.",
      "20. Cierra sellando con cera.",
    ],
    warnings: "Puede generar obsesión intensa.",
    notes: "Usar con intención clara.",
    essenceCost: 235,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 21,
  },
  {
    title: "Endulzamiento con Vainilla y Piloncillo",
    slug: "endulzamiento-vainilla-piloncillo",
    summary:
      "Endulzamiento suave para mejorar relaciones familiares y románticas.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 35,
    origin:
      "Tradición de rancho mexicano. Ingredientes comunes en cocina y magia diaria.",
    intention: "Traer dulzura y armonía.",
    expectedResult: "Mayor cariño y paz.",
    repeatEvery: "Miércoles",
    tags: ["endulzamiento", "vainilla", "piloncillo"],
    ingredients: [
      "Vainilla (extracto)",
      "Piloncillo",
      "Miel",
      "Velas rosas",
      "Nombres",
    ],
    steps: [
      "1. Enciende velas rosas.",
      "2. Derrite piloncillo.",
      "3. Agrega vainilla y miel.",
      "4. Coloca nombres.",
      "5. Mezcla en sentido horario.",
      "6. Recita oración de dulzura.",
      "7. Deja reposar 21 minutos.",
      "8. Unta en foto o objeto.",
      "9. Repite durante 7 días.",
      "10. Ofrece flores.",
      "11. Visualiza armonía.",
      "12. Quema velas diarias.",
      "13. Guarda mezcla.",
      "14. Observa cambios.",
      "15. Refuerza semanal.",
      "16. Da gracias.",
      "17. Limpia altar.",
      "18. Cierra ritual.",
      "19. Comparte dulzura.",
      "20. Mantén positivo.",
    ],
    warnings: "Efecto temporal.",
    notes: "Ideal para sanar lazos.",
    essenceCost: 160,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 22,
  },
  {
    title: "Separación con Ajo y Sal Negra",
    slug: "separacion-ajo-sal-negra",
    summary:
      "Separación fuerte usando ajo y sal negra para eliminar lazos tóxicos.",
    category: "SEPARATION",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 45,
    origin: "Limpias y brujería rural mexicana.",
    intention: "Cortar conexiones dañinas.",
    expectedResult: "Liberación y distanciamiento.",
    repeatEvery: "Luna menguante",
    tags: ["separacion", "ajo", "sal-negra"],
    ingredients: [
      "Ajos (7)",
      "Sal negra",
      "Velas negras",
      "Papel con nombres",
      "Hilo negro",
    ],
    steps: [
      "1. Machaca los ajos.",
      "2. Mezcla con sal negra.",
      "3. Escribe nombres en papel.",
      "4. Envuelve con hilo negro.",
      "5. Enciende velas negras.",
      "6. Recita oración de corte.",
      "7. Esparce mezcla alrededor.",
      "8. Entierra lejos de casa.",
      "9. Repite 9 días.",
      "10. Limpia con copal.",
      "11. Observa distanciamiento.",
      "12. Refuerza con sal.",
      "13. Da gracias.",
      "14. Protege energía.",
      "15. Quema papel.",
      "16. Limpia hogar.",
      "17. Visualiza libertad.",
      "18. Ofrece.",
      "19. Cierra ciclo.",
      "20. Confirma paz.",
    ],
    warnings: "Realizar limpia personal.",
    notes: "Para protección propia.",
    essenceCost: 195,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 23,
  },
  {
    title: "Dominación con Veladora Roja y Clavos",
    slug: "dominacion-veladora-roja-clavos",
    summary:
      "Dominación usando veladora roja y clavos para someter voluntades.",
    category: "DOMINATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 60,
    origin: "Brujería de rancho y sincretismo católico mexicano.",
    intention: "Dominar situación o persona.",
    expectedResult: "Control y obediencia.",
    repeatEvery: "Martes",
    tags: ["dominacion", "veladora", "clavos"],
    ingredients: ["Veladora roja", "Clavos (13)", "Foto", "Aceite", "Polvos"],
    steps: [
      "1. Unta veladora con aceite.",
      "2. Clava los 13 clavos en foto.",
      "3. Enciende veladora.",
      "4. Invoca santo fuerte.",
      "5. Recita mandamientos.",
      "6. Visualiza control.",
      "7. Repite 13 días.",
      "8. Ofrece tabaco.",
      "9. Refuerza polvos.",
      "10. Observa sumisión.",
      "11. Protege contra reversa.",
      "12. Da gracias.",
      "13. Limpia residuos.",
      "14. Almacena restos.",
      "15. Repite según necesidad.",
      "16. Cierra con sal.",
      "17. Reflexiona ética.",
      "18. Invoca protección.",
      "19. Finaliza.",
      "20. Agradece.",
    ],
    warnings: "Alto riesgo de reversa.",
    notes: "Solo para casos justos.",
    essenceCost: 280,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 24,
  },
  {
    title: "Endulzamiento con Canela y Miel de Abeja",
    slug: "endulzamiento-canela-miel-abeja",
    summary: "Endulzamiento clásico con canela y miel para atraer afecto.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 30,
    origin: "Tradiciones hogareñas mexicanas.",
    intention: "Suavizar corazón.",
    expectedResult: "Cariño y cercanía.",
    repeatEvery: "Viernes",
    tags: ["endulzamiento", "canela", "miel"],
    ingredients: ["Canela", "Miel de abeja", "Velas rosas", "Foto"],
    steps: [
      "1. Enciende velas.",
      "2. Vierte miel.",
      "3. Esparce canela.",
      "4. Coloca foto.",
      "5. Mezcla.",
      "6. Recita.",
      "7. Deja reposar.",
      "8. Unta foto.",
      "9. Repite 7 días.",
      "10. Ofrece.",
      "11. Visualiza.",
      "12. Quema velas.",
      "13. Guarda.",
      "14. Observa.",
      "15. Refuerza.",
      "16. Gracias.",
      "17. Limpia.",
      "18. Cierra.",
      "19. Comparte.",
      "20. Mantén.",
    ],
    warnings: "Reforzar regularmente.",
    notes: "Buen uso amoroso.",
    essenceCost: 150,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 25,
  },
  {
    title: "Amarre con Cuerda Roja y Cabello",
    slug: "amarre-cuerda-roja-cabello",
    summary: "Amarre tradicional con cuerda roja y cabello para unión fuerte.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 55,
    origin: "Folklore mestizo mexicano.",
    intention: "Atar destinos.",
    expectedResult: "Lealtad permanente.",
    repeatEvery: "Luna creciente",
    tags: ["amarre", "cuerda-roja", "cabello"],
    ingredients: ["Cuerda roja", "Cabello", "Velas rojas", "Agujas"],
    steps: [
      "1. Enciende velas.",
      "2. Ata cabello con cuerda.",
      "3. Forma nudos fuertes.",
      "4. Clava agujas.",
      "5. Recita ensalmo.",
      "6. Visualiza lazo.",
      "7. Repite noches.",
      "8. Ofrece copal.",
      "9. Entierra.",
      "10. Mantén.",
      "11. Refuerza.",
      "12. Invoca.",
      "13. Observa.",
      "14. Protege.",
      "15. Gracias.",
      "16. Limpia.",
      "17. Repite.",
      "18. Alimenta.",
      "19. Cierra.",
      "20. Sellado.",
    ],
    warnings: "Fuerte dominio.",
    notes: "Consecuencias kármicas.",
    essenceCost: 225,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 26,
  },
  {
    title: "Separación con Chile y Hilo Negro",
    slug: "separacion-chile-hilo-negro",
    summary: "Separación picante usando chile y hilo negro.",
    category: "SEPARATION",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    origin: "Brujería popular mexicana.",
    intention: "Cortar lazos.",
    expectedResult: "Distanciamiento.",
    repeatEvery: "Luna menguante",
    tags: ["separacion", "chile", "hilo-negro"],
    ingredients: ["Chiles secos", "Hilo negro", "Velas negras", "Sal"],
    steps: [
      "1. Ata chiles con hilo.",
      "2. Nombres dentro.",
      "3. Enciende velas.",
      "4. Recita corte.",
      "5. Esparce sal.",
      "6. Entierra.",
      "7. Repite.",
      "8. Limpia.",
      "9. Observa.",
      "10. Refuerza.",
      "11. Gracias.",
      "12. Protege.",
      "13. Quema.",
      "14. Limpia hogar.",
      "15. Visualiza.",
      "16. Ofrece.",
      "17. Cierra.",
      "18. Sal casa.",
      "19. Finaliza.",
      "20. Confirma.",
    ],
    warnings: "Energía fuerte.",
    notes: "Para bien mayor.",
    essenceCost: 200,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 27,
  },
  {
    title: "Dominación con San Marcos y Aceite",
    slug: "dominacion-san-marcos-aceite",
    summary: "Dominación invocando San Marcos con aceite consagrado.",
    category: "DOMINATION",
    accessLevel: "RESERVED",
    difficulty: "ADVANCED",
    estimatedMinutes: 65,
    origin: "Sincretismo católico mexicano.",
    intention: "Dominar mediante santo.",
    expectedResult: "Obediencia.",
    repeatEvery: "Martes",
    tags: ["dominacion", "san-marcos", "aceite"],
    ingredients: ["Veladora San Marcos", "Aceite", "Foto", "Clavos"],
    steps: [
      "1. Unta veladora.",
      "2. Coloca foto.",
      "3. Enciende.",
      "4. Invoca San Marcos.",
      "5. Recita.",
      "6. Visualiza.",
      "7. Repite.",
      "8. Ofrece.",
      "9. Refuerza.",
      "10. Observa.",
      "11. Protege.",
      "12. Gracias.",
      "13. Limpia.",
      "14. Almacena.",
      "15. Repite.",
      "16. Cierra.",
      "17. Reflexiona.",
      "18. Invoca.",
      "19. Finaliza.",
      "20. Agradece.",
    ],
    warnings: "Respeto máximo.",
    notes: "Solo justicia.",
    essenceCost: 275,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 28,
  },
  {
    title: "Endulzamiento con Rosas Rojas y Azúcar",
    slug: "endulzamiento-rosas-rojas-azucar",
    summary: "Endulzamiento floral con rosas rojas para amor.",
    category: "SWEETENING",
    accessLevel: "PUBLIC",
    difficulty: "EASY",
    estimatedMinutes: 40,
    origin: "Folklore mexicano con flores.",
    intention: "Atraer dulzura amorosa.",
    expectedResult: "Cariño floreciente.",
    repeatEvery: "Viernes",
    tags: ["endulzamiento", "rosas-rojas", "azucar"],
    ingredients: ["Rosas rojas", "Azúcar", "Miel", "Velas"],
    steps: [
      "1. Enciende velas.",
      "2. Pétalos de rosas.",
      "3. Mezcla azúcar.",
      "4. Agrega miel.",
      "5. Coloca nombres.",
      "6. Recita.",
      "7. Mezcla.",
      "8. Deja.",
      "9. Unta.",
      "10. Repite.",
      "11. Ofrece rosas.",
      "12. Visualiza.",
      "13. Guarda.",
      "14. Observa.",
      "15. Refuerza.",
      "16. Gracias.",
      "17. Limpia.",
      "18. Cierra.",
      "19. Comparte.",
      "20. Finaliza.",
    ],
    warnings: "Mantener positivo.",
    notes: "Armonía.",
    essenceCost: 170,
    requiresDisclaimer: false,
    disclaimerVersion: null,
    isPublished: true,
    sortOrder: 29,
  },
  {
    title: "Amarre Eterno con Ixtle y Cempasúchil",
    slug: "amarre-eterno-ixtle-cempasuchil",
    summary: "Amarre eterno usando ixtle y cempasúchil.",
    category: "BINDING",
    accessLevel: "PREMIUM",
    difficulty: "MEDIUM",
    estimatedMinutes: 70,
    origin: "Tradición nahua prehispánica.",
    intention: "Unión más allá de la vida.",
    expectedResult: "Permanencia eterna.",
    repeatEvery: "Luna llena",
    tags: ["amarre", "ixtle", "cempasuchil"],
    ingredients: [
      "Cuerda de ixtle",
      "Pétalos de cempasúchil",
      "Cabello",
      "Velas",
    ],
    steps: [
      "1. Enciende velas.",
      "2. Ata con ixtle.",
      "3. Agrega pétalos.",
      "4. Nudos fuertes.",
      "5. Invoca ancestros.",
      "6. Visualiza eterno.",
      "7. Repite.",
      "8. Ofrece.",
      "9. Entierra.",
      "10. Mantén.",
      "11. Refuerza.",
      "12. Ancestros.",
      "13. Observa.",
      "14. Protege.",
      "15. Gracias.",
      "16. Limpia.",
      "17. Repite.",
      "18. Alimenta.",
      "19. Cierra.",
      "20. Eterno.",
    ],
    warnings: "Muy fuerte.",
    notes: "Respeto ancestral.",
    essenceCost: 255,
    requiresDisclaimer: true,
    disclaimerVersion: "1.0",
    isPublished: true,
    sortOrder: 30,
  },
];

async function main() {
  for (const ritual of grimoireRituals) {
    const data = {
      ...ritual,
      tags: [...ritual.tags],
      ingredients: [...ritual.ingredients],
      steps: [...ritual.steps],
    };

    await prisma.grimoireRitual.upsert({
      where: {
        slug: data.slug,
      },
      update: data as any,
      create: data as any,
    });
  }

  const total = await prisma.grimoireRitual.count();
  console.log(
    `✅ Seed completado correctamente. ${total} rituales disponibles en el Grimorio.`,
  );
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
