import type { TarotCard } from "./tarot.types";

const CARD_BASE_PATH = "/cards/tarot";

export const TAROT_DECK: TarotCard[] = [
  {
    id: "el_loco",
    name: "El Loco",
    slug: "el_loco",
    imageSrc: `${CARD_BASE_PATH}/el_loco.png`,
    arcana: "MAJOR",
    number: 0,
  },
  {
    id: "el_mago",
    name: "El Mago",
    slug: "el_mago",
    imageSrc: `${CARD_BASE_PATH}/el_mago.png`,
    arcana: "MAJOR",
    number: 1,
  },
  {
    id: "la_sacerdotisa",
    name: "La Sacerdotisa",
    slug: "la_sacerdotisa",
    imageSrc: `${CARD_BASE_PATH}/la_sacerdotisa.png`,
    arcana: "MAJOR",
    number: 2,
  },
  {
    id: "la_emperatriz",
    name: "La Emperatriz",
    slug: "la_emperatriz",
    imageSrc: `${CARD_BASE_PATH}/la_emperatriz.png`,
    arcana: "MAJOR",
    number: 3,
  },
  {
    id: "el_emperador",
    name: "El Emperador",
    slug: "el_emperador",
    imageSrc: `${CARD_BASE_PATH}/el_emperador.png`,
    arcana: "MAJOR",
    number: 4,
  },
  {
    id: "el_hierofante",
    name: "El Hierofante",
    slug: "el_hierofante",
    imageSrc: `${CARD_BASE_PATH}/el_hierofante.png`,
    arcana: "MAJOR",
    number: 5,
  },
  {
    id: "los_enamorados",
    name: "Los Enamorados",
    slug: "los_enamorados",
    imageSrc: `${CARD_BASE_PATH}/los_enamorados.png`,
    arcana: "MAJOR",
    number: 6,
  },
  {
    id: "el_carro",
    name: "El Carro",
    slug: "el_carro",
    imageSrc: `${CARD_BASE_PATH}/el_carro.png`,
    arcana: "MAJOR",
    number: 7,
  },
  {
    id: "la_fuerza",
    name: "La Fuerza",
    slug: "la_fuerza",
    imageSrc: `${CARD_BASE_PATH}/la_fuerza.png`,
    arcana: "MAJOR",
    number: 8,
  },
  {
    id: "el_ermitano",
    name: "El Ermitaño",
    slug: "el_ermitano",
    imageSrc: `${CARD_BASE_PATH}/el_ermitano.png`,
    arcana: "MAJOR",
    number: 9,
  },
  {
    id: "la_ruedadelafortuna",
    name: "La Rueda de la Fortuna",
    slug: "la_ruedadelafortuna",
    imageSrc: `${CARD_BASE_PATH}/la_ruedadelafortuna.png`,
    arcana: "MAJOR",
    number: 10,
  },
  {
    id: "la_justicia",
    name: "La Justicia",
    slug: "la_justicia",
    imageSrc: `${CARD_BASE_PATH}/la_justicia.png`,
    arcana: "MAJOR",
    number: 11,
  },
  {
    id: "el_colgado",
    name: "El Colgado",
    slug: "el_colgado",
    imageSrc: `${CARD_BASE_PATH}/el_colgado.png`,
    arcana: "MAJOR",
    number: 12,
  },
  {
    id: "la_muerte",
    name: "La Muerte",
    slug: "la_muerte",
    imageSrc: `${CARD_BASE_PATH}/la_muerte.png`,
    arcana: "MAJOR",
    number: 13,
  },
  {
    id: "la_templanza",
    name: "La Templanza",
    slug: "la_templanza",
    imageSrc: `${CARD_BASE_PATH}/la_templanza.png`,
    arcana: "MAJOR",
    number: 14,
  },
  {
    id: "el_diablo",
    name: "El Diablo",
    slug: "el_diablo",
    imageSrc: `${CARD_BASE_PATH}/el_diablo.png`,
    arcana: "MAJOR",
    number: 15,
  },
  {
    id: "la_torre",
    name: "La Torre",
    slug: "la_torre",
    imageSrc: `${CARD_BASE_PATH}/la_torre.png`,
    arcana: "MAJOR",
    number: 16,
  },
  {
    id: "la_estrella",
    name: "La Estrella",
    slug: "la_estrella",
    imageSrc: `${CARD_BASE_PATH}/la_estrella.png`,
    arcana: "MAJOR",
    number: 17,
  },
  {
    id: "la_luna",
    name: "La Luna",
    slug: "la_luna",
    imageSrc: `${CARD_BASE_PATH}/la_luna.png`,
    arcana: "MAJOR",
    number: 18,
  },
  {
    id: "el_sol",
    name: "El Sol",
    slug: "el_sol",
    imageSrc: `${CARD_BASE_PATH}/el_sol.png`,
    arcana: "MAJOR",
    number: 19,
  },
  {
    id: "el_juicio",
    name: "El Juicio",
    slug: "el_juicio",
    imageSrc: `${CARD_BASE_PATH}/el_juicio.png`,
    arcana: "MAJOR",
    number: 20,
  },
  {
    id: "el_mundo",
    name: "El Mundo",
    slug: "el_mundo",
    imageSrc: `${CARD_BASE_PATH}/el_mundo.png`,
    arcana: "MAJOR",
    number: 21,
  },

  {
    id: "as_de_bastos",
    name: "As de Bastos",
    slug: "as_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/as_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 1,
  },
  {
    id: "dos_de_bastos",
    name: "Dos de Bastos",
    slug: "dos_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/dos_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 2,
  },
  {
    id: "tres_de_bastos",
    name: "Tres de Bastos",
    slug: "tres_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/tres_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 3,
  },
  {
    id: "cuatro_de_bastos",
    name: "Cuatro de Bastos",
    slug: "cuatro_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/cuatro_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 4,
  },
  {
    id: "cinco_de_bastos",
    name: "Cinco de Bastos",
    slug: "cinco_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/cinco_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 5,
  },
  {
    id: "seis_de_bastos",
    name: "Seis de Bastos",
    slug: "seis_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/seis_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 6,
  },
  {
    id: "siete_de_bastos",
    name: "Siete de Bastos",
    slug: "siete_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/siete_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 7,
  },
  {
    id: "ocho_de_bastos",
    name: "Ocho de Bastos",
    slug: "ocho_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/ocho_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 8,
  },
  {
    id: "nueve_de_bastos",
    name: "Nueve de Bastos",
    slug: "nueve_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/nueve_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 9,
  },
  {
    id: "diez_de_bastos",
    name: "Diez de Bastos",
    slug: "diez_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/diez_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 10,
  },
  {
    id: "sota_de_bastos",
    name: "Sota de Bastos",
    slug: "sota_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/sota_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 11,
  },
  {
    id: "caballero_de_bastos",
    name: "Caballero de Bastos",
    slug: "caballero_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/caballero_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 12,
  },
  {
    id: "reina_de_bastos",
    name: "Reina de Bastos",
    slug: "reina_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/reina_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 13,
  },
  {
    id: "rey_de_bastos",
    name: "Rey de Bastos",
    slug: "rey_de_bastos",
    imageSrc: `${CARD_BASE_PATH}/rey_de_bastos.png`,
    arcana: "MINOR",
    suit: "WANDS",
    number: 14,
  },

  {
    id: "as_de_copas",
    name: "As de Copas",
    slug: "as_de_copas",
    imageSrc: `${CARD_BASE_PATH}/as_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 1,
  },
  {
    id: "dos_de_copas",
    name: "Dos de Copas",
    slug: "dos_de_copas",
    imageSrc: `${CARD_BASE_PATH}/dos_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 2,
  },
  {
    id: "tres_de_copas",
    name: "Tres de Copas",
    slug: "tres_de_copas",
    imageSrc: `${CARD_BASE_PATH}/tres_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 3,
  },
  {
    id: "cuatro_de_copas",
    name: "Cuatro de Copas",
    slug: "cuatro_de_copas",
    imageSrc: `${CARD_BASE_PATH}/cuatro_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 4,
  },
  {
    id: "cinco_de_copas",
    name: "Cinco de Copas",
    slug: "cinco_de_copas",
    imageSrc: `${CARD_BASE_PATH}/cinco_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 5,
  },
  {
    id: "seis_de_copas",
    name: "Seis de Copas",
    slug: "seis_de_copas",
    imageSrc: `${CARD_BASE_PATH}/seis_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 6,
  },
  {
    id: "siete_de_copas",
    name: "Siete de Copas",
    slug: "siete_de_copas",
    imageSrc: `${CARD_BASE_PATH}/siete_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 7,
  },
  {
    id: "ocho_de_copas",
    name: "Ocho de Copas",
    slug: "ocho_de_copas",
    imageSrc: `${CARD_BASE_PATH}/ocho_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 8,
  },
  {
    id: "nueve_de_copas",
    name: "Nueve de Copas",
    slug: "nueve_de_copas",
    imageSrc: `${CARD_BASE_PATH}/nueve_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 9,
  },
  {
    id: "diez_de_copas",
    name: "Diez de Copas",
    slug: "diez_de_copas",
    imageSrc: `${CARD_BASE_PATH}/diez_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 10,
  },
  {
    id: "sota_de_copas",
    name: "Sota de Copas",
    slug: "sota_de_copas",
    imageSrc: `${CARD_BASE_PATH}/sota_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 11,
  },
  {
    id: "caballero_de_copas",
    name: "Caballero de Copas",
    slug: "caballero_de_copas",
    imageSrc: `${CARD_BASE_PATH}/caballero_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 12,
  },
  {
    id: "reina_de_copas",
    name: "Reina de Copas",
    slug: "reina_de_copas",
    imageSrc: `${CARD_BASE_PATH}/reina_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 13,
  },
  {
    id: "rey_de_copas",
    name: "Rey de Copas",
    slug: "rey_de_copas",
    imageSrc: `${CARD_BASE_PATH}/rey_de_copas.png`,
    arcana: "MINOR",
    suit: "CUPS",
    number: 14,
  },

  {
    id: "as_de_espadas",
    name: "As de Espadas",
    slug: "as_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/as_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 1,
  },
  {
    id: "dos_de_espadas",
    name: "Dos de Espadas",
    slug: "dos_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/dos_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 2,
  },
  {
    id: "tres_de_espadas",
    name: "Tres de Espadas",
    slug: "tres_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/tres_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 3,
  },
  {
    id: "cuatro_de_espadas",
    name: "Cuatro de Espadas",
    slug: "cuatro_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/cuatro_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 4,
  },
  {
    id: "cinco_de_espadas",
    name: "Cinco de Espadas",
    slug: "cinco_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/cinco_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 5,
  },
  {
    id: "seis_de_espadas",
    name: "Seis de Espadas",
    slug: "seis_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/seis_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 6,
  },
  {
    id: "siete_de_espadas",
    name: "Siete de Espadas",
    slug: "siete_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/siete_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 7,
  },
  {
    id: "ocho_de_espadas",
    name: "Ocho de Espadas",
    slug: "ocho_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/ocho_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 8,
  },
  {
    id: "nueve_de_espadas",
    name: "Nueve de Espadas",
    slug: "nueve_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/nueve_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 9,
  },
  {
    id: "diez_de_espadas",
    name: "Diez de Espadas",
    slug: "diez_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/diez_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 10,
  },
  {
    id: "sota_de_espadas",
    name: "Sota de Espadas",
    slug: "sota_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/sota_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 11,
  },
  {
    id: "caballero_de_espadas",
    name: "Caballero de Espadas",
    slug: "caballero_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/caballero_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 12,
  },
  {
    id: "reina_de_espadas",
    name: "Reina de Espadas",
    slug: "reina_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/reina_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 13,
  },
  {
    id: "rey_de_espadas",
    name: "Rey de Espadas",
    slug: "rey_de_espadas",
    imageSrc: `${CARD_BASE_PATH}/rey_de_espadas.png`,
    arcana: "MINOR",
    suit: "SWORDS",
    number: 14,
  },

  {
    id: "as_de_pentaculos",
    name: "As de Pentáculos",
    slug: "as_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/as_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 1,
  },
  {
    id: "dos_de_pentaculos",
    name: "Dos de Pentáculos",
    slug: "dos_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/dos_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 2,
  },
  {
    id: "tres_de_pentaculos",
    name: "Tres de Pentáculos",
    slug: "tres_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/tres_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 3,
  },
  {
    id: "cuatro_de_pentaculos",
    name: "Cuatro de Pentáculos",
    slug: "cuatro_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/cuatro_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 4,
  },
  {
    id: "cinco_de_pentaculos",
    name: "Cinco de Pentáculos",
    slug: "cinco_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/cinco_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 5,
  },
  {
    id: "seis_de_pentaculos",
    name: "Seis de Pentáculos",
    slug: "seis_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/seis_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 6,
  },
  {
    id: "siete_de_pentaculos",
    name: "Siete de Pentáculos",
    slug: "siete_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/siete_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 7,
  },
  {
    id: "ocho_de_pentaculos",
    name: "Ocho de Pentáculos",
    slug: "ocho_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/ocho_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 8,
  },
  {
    id: "nueve_de_pentaculos",
    name: "Nueve de Pentáculos",
    slug: "nueve_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/nueve_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 9,
  },
  {
    id: "diez_de_pentaculos",
    name: "Diez de Pentáculos",
    slug: "diez_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/diez_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 10,
  },
  {
    id: "sota_de_pentaculos",
    name: "Sota de Pentáculos",
    slug: "sota_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/sota_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 11,
  },
  {
    id: "caballero_de_pentaculos",
    name: "Caballero de Pentáculos",
    slug: "caballero_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/caballero_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 12,
  },
  {
    id: "reina_de_pentaculos",
    name: "Reina de Pentáculos",
    slug: "reina_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/reina_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 13,
  },
  {
    id: "rey_de_pentaculos",
    name: "Rey de Pentáculos",
    slug: "rey_de_pentaculos",
    imageSrc: `${CARD_BASE_PATH}/rey_de_pentaculos.png`,
    arcana: "MINOR",
    suit: "PENTACLES",
    number: 14,
  },
];